### ISSUE TITLE
keyCreator() Lacks Dupe Protection

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#1]
> `function` keyCreator() {

    let alphabet = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p",
    "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"];
    return alphabet[Math.floor(Math.random() * 25)] + alphabet[Math.floor(Math.random() * 25)] + alphabet[Math.floor(Math.random() * 25)] + alphabet[Math.floor(Math.random() * 25)] + alphabet[Math.floor(Math.random() * 25)];
}

No code to mitigate the possibility of multiple rooms created with the same key - suggest an if statement before returning key to check whether key has already been created.

**Comment by DannyOppenheimer** [comment]
A simple if statement won't be enough, as if the user clicks the create button and it creates a dupe key they'll have to spam it again, need a better idea. By the way, I'm storing all active game rooms in a json file that looks like this:
`
{
    "rooms": {
        "asjen": {}
    }
}
`

**Comment by AndrewLester** [comment]
You could do a while loop

**Comment by DannyOppenheimer** [comment]
1401bc20d3e0c3aab88854c066da5bd0537b8a8c
