### ISSUE TITLE
Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#11]
This issue should be resolved if we move to HTTPS but right now our server wildcard is configured as "*" which is problematic. 

Can be resolved through MDN web docs: 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by JonathanOppenheimer** [comment]
Here's an article about what wildcards are/do
https://www.cbtnuggets.com/blog/technology/networking/networking-basics-what-are-wildcard-masks-and-how-do-they-work

**Comment by DannyOppenheimer** [comment]
Thanks for the article, it makes more sense now.

No idea how to implement this into node, and there are no tutorials. I'll probably just figure out HTTPS first since that's going to happen eventually anyway.

**Comment by JonathanOppenheimer** [comment]
Issue resolved through migration to HTTPS
