### ISSUE TITLE
Use of Mutation Events is deprecated. Use MutationObserver instead.

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#12]
Error is contained in jquery-3.3.1.min.js - no idea how to fix this but maybe we need to update jquery?

**Comment by JonathanOppenheimer** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver

**Comment by DannyOppenheimer** [comment]
I do not use jQuery, this shouldn't be applicable

**Comment by DannyOppenheimer** [comment]
Closing for now, if it comes up again, reopen the issue
