### ISSUE TITLE
Location listing fails to populate upon starting game

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#13]
Currently, the following is displayed upon starting a game with both locations selected

> Location Reference:
>
>If you can read this your game is not working correctly.
>
>If you can read this your game is not working correctly.

**Comment by DannyOppenheimer** [comment]
Yes, I haven't coded this yet.

**Comment by DannyOppenheimer** [comment]
Implemented in commit:
f4c4691bfdb0455d2221965195929ab4d0676464
Next, I need to add the ability to toggle the player names and location names on and off
