### ISSUE TITLE
Fonts not contained within repo 

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#2]
>   `<link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">`

Font used on all HTML pages is not contained with the repository but is stored on a third party - consider localizing the ttf

**Comment by AndrewLester** [comment]
Using the link appears to be the suggested implementation: https://developers.google.com/fonts/docs/getting_started#a_quick_example

Consider closing this issue.

**Comment by DannyOppenheimer** [comment]
I can very easily use a ttf as well.
Which do you think is a better option?

**Comment by AndrewLester** [comment]
I would stick with google's api. Check out this page for an explanation of everything they do for you: https://developers.google.com/fonts/docs/technical_considerations

**Comment by DannyOppenheimer** [comment]
Bet
