### ISSUE TITLE
Something other than JSON file for in progress games

### ISSUE THREAD

**Issue by AndrewLester** [DannyOppenheimer/SpyFall#4]
Reading/writing to and from the JSON file while the app is up is probably not going to be effective during usage. I would suggest something like Redis. 
Heroku: https://devcenter.heroku.com/articles/heroku-redis
NodeJS: https://github.com/NodeRedis/node_redis

Maybe something for after this actually gets up and running...

**Comment by DannyOppenheimer** [comment]
Not going to use JSON anymore, just an array. It doesn't matter if the rooms are wiped on the program close, because it's not like people will be able to use the same room again anyway.

**Comment by DannyOppenheimer** [comment]
1401bc20d3e0c3aab88854c066da5bd0537b8a8c
