### ISSUE TITLE
Port # choice

### ISSUE THREAD

**Issue by DannyOppenheimer** [DannyOppenheimer/SpyFall#5]
I'm about to set up port forwarding with verizon, is there standard or customary port to use with websites, or just anything? I know it's by default to use port 25565 for Minecraft servers so I was wondering if there was a 'default' for websites.

**Comment by AndrewLester** [comment]
Well port 80 is for HTTP and port 443 is for HTTPS.

**Comment by DannyOppenheimer** [comment]
Do you think I should try and implement https or is it not worth

**Comment by AndrewLester** [comment]
No, as you'd need to do it through a company. I don't really know how it works too well though. It's definitely possible, but if you're gonna do it you should probably get some hosting too.

**Comment by DannyOppenheimer** [comment]
Using port 80 for now will use port 443 if we ever get HTTPS working.
