### ISSUE TITLE
.html extension still in links

### ISSUE THREAD

**Issue by DannyOppenheimer** [DannyOppenheimer/SpyFall#7]
It doesn't really matter, but it's always annoyed me when links still have the .html extension in them. By searching around, most people suggest to put a .htaccess in the root with the following code:

```
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\.html -f
RewriteRule ^(.*)$ $1.html
```

Although I'm pretty that only works when you use Apache. Is there any other ways to get rid of the .html?

**Comment by AndrewLester** [comment]
https://expressjs.com/en/guide/routing.html

**Comment by DannyOppenheimer** [comment]
Will leave this issue open for now – don't know how to follow a link from the backend rn so I'll read and then close when I figure it out.

**Comment by DannyOppenheimer** [comment]
Why do you assign Andrew to everything lmao?

**Comment by JonathanOppenheimer** [comment]
cause it's a funi but i guess andy doesn't wanna do this one :(((

**Comment by DannyOppenheimer** [comment]
Fixed in commit

9d34a56730a2d61652c5e8a0e520458b390a22e0

with method:
```
app.use(
	serveStatic('frontend', {
		extensions: ['html']
	})
);
```

using the node module "serve-static"
