### ISSUE TITLE
Vertical User Stack

### ISSUE THREAD

**Issue by JonathanOppenheimer** [DannyOppenheimer/SpyFall#8]
Vertical stack of joined players make page clunky and annoying to use - change to 3 x L imo

**Comment by DannyOppenheimer** [comment]
I tried to do 2x before, but idk how to do it because I need to know before assigning the values whether or not to add another cell or not in the for loop. You need to like look into the next loop and get that value its weird

**Comment by AndrewLester** [comment]
Just make it a flex box and you don't have to worry about js.

**Comment by DannyOppenheimer** [comment]
Fixed in commit:
0e4286fdedbd8b178fe71788c460744abdc2d436

Using inline-block, and a calc() to get the screen size and drop players to the next line.
