### ISSUE TITLE
Blocked by iBoss

### ISSUE THREAD

**Issue by quirozj** [DannyOppenheimer/SpyFall#9]
Very unhappy. Was looking forward to using this product and I was redirected to a web page saying it was blocked by something called "iBoss"!!! Outrageous!!!

0/5 stars!

**Comment by donovanj44** [comment]
I've heard that iBoss only blocks malicious sites. Maybe this website is only made to harm computers! I think we need to report it to GitHub immediately!

**Comment by DannyOppenheimer** [comment]
Don't tell the authorities 🤫

![Buying Medicine Online](https://user-images.githubusercontent.com/57159537/73700633-0bd8bd80-46b5-11ea-9000-d424aa8ec654.jpg)

**Comment by TheBlueness** [comment]
I love my brother.

**Comment by DannyOppenheimer** [comment]
The issue was fixed. Implemented the Helmet node for extra security, might have made iBoss let it through.
